### ISSUE TITLE
Does not build with Swift 5.3 and in Linux

### ISSUE THREAD

**Issue by Dadoum** [therecipe/swift#1]
FIrst, internal.swift misses:
```swift
import CoreFoundation
import FoundationNetworking
```
and after, the process will abandon:
```
Could not cast value of type 'app.QJSValue' (0x5652663cb140) to 'Foundation.NSObject' (0x7fe7cf083050).
```

**Comment by therecipe** [comment]
Hey

I looked into this and https://github.com/therecipe/swift/commit/fee2fa3b9efd34a4f2588b413c58bd1693e7a2ec should fix this now.
Btw, could you kindly report if the speed of the pixel editor is acceptable?
I just tested it with a rather underpowered vm and it was pretty sluggish for me.

**Comment by Dadoum** [comment]
It works well, it flickers a bit when it is resized,but no more problem on compilation.

**Comment by therecipe** [comment]
Thanks for the update, feel free to hit me up if you encounter any issues using the binding.
